version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: fincheck-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: fincheck
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
